# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/yannv/Documents/Projets_HW/PacMan/PacMan_v2_AIO/Pacman_Artyx7/Pacman_Artyx7.srcs/sources_1/ip/rom_pacman_1m/rom_pacman_1m.xci
# IP: The module: 'rom_pacman_1m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yannv/Documents/Projets_HW/PacMan/PacMan_v2_AIO/Pacman_Artyx7/Pacman_Artyx7.gen/sources_1/ip/rom_pacman_1m/rom_pacman_1m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_pacman_1m'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/yannv/Documents/Projets_HW/PacMan/PacMan_v2_AIO/Pacman_Artyx7/Pacman_Artyx7.srcs/sources_1/ip/rom_pacman_1m/rom_pacman_1m.xci
# IP: The module: 'rom_pacman_1m' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yannv/Documents/Projets_HW/PacMan/PacMan_v2_AIO/Pacman_Artyx7/Pacman_Artyx7.gen/sources_1/ip/rom_pacman_1m/rom_pacman_1m_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_pacman_1m'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
