# Timings constraints
# Ignore input delays related to input ports (R, G, B,...)





set_false_path -to [get_ports *o_dip*]
set_false_path -to [get_ports *o_in*]

set_property PACKAGE_PIN P17 [get_ports i_clk_sys]
set_property PACKAGE_PIN D3 [get_ports i_cpu_m1_l_core]
set_property PACKAGE_PIN J3 [get_ports i_cpu_mreq_l_core]
set_property PACKAGE_PIN G2 [get_ports i_cpu_rd_l_core]
set_property PACKAGE_PIN K1 [get_ports i_cpu_wr_l_core]
set_property PACKAGE_PIN A1 [get_ports o_cpu_clk_core]
set_property PACKAGE_PIN D4 [get_ports o_flash_cs_l_core]
set_property PACKAGE_PIN E1 [get_ports o_do_core_enable_n]


# Bus adresses CPU
set_property PACKAGE_PIN A6 [get_ports {i_cpu_a_core[11]}]
set_property PACKAGE_PIN E5 [get_ports {i_cpu_a_core[4]}]
set_property PACKAGE_PIN D8 [get_ports {i_cpu_a_core[12]}]
set_property PACKAGE_PIN B6 [get_ports {i_cpu_a_core[2]}]
set_property PACKAGE_PIN F6 [get_ports {i_cpu_a_core[14]}]
set_property PACKAGE_PIN B7 [get_ports {i_cpu_a_core[10]}]
set_property PACKAGE_PIN C4 [get_ports {i_cpu_a_core[9]}]
set_property PACKAGE_PIN C7 [get_ports {i_cpu_a_core[7]}]
set_property PACKAGE_PIN D7 [get_ports {i_cpu_a_core[5]}]
set_property PACKAGE_PIN C5 [get_ports {i_cpu_a_core[0]}]
set_property PACKAGE_PIN A5 [get_ports {i_cpu_a_core[3]}]
set_property PACKAGE_PIN B4 [get_ports {i_cpu_a_core[1]}]
set_property PACKAGE_PIN E6 [get_ports {i_cpu_a_core[15]}]
set_property PACKAGE_PIN E7 [get_ports {i_cpu_a_core[13]}]

# Bus FPGA vers CPU
set_property PACKAGE_PIN P2 [get_ports {o_cpu_di_core[7]}]
set_property PACKAGE_PIN N2 [get_ports {o_cpu_di_core[6]}]
set_property PACKAGE_PIN L1 [get_ports {o_cpu_di_core[5]}]
set_property PACKAGE_PIN M2 [get_ports {o_cpu_di_core[4]}]
set_property PACKAGE_PIN R1 [get_ports {o_cpu_di_core[3]}]
set_property PACKAGE_PIN R3 [get_ports {o_cpu_di_core[2]}]
set_property PACKAGE_PIN M4 [get_ports {o_cpu_di_core[0]}]

# Bus CPU vers FPGA
set_property PACKAGE_PIN F4 [get_ports {i_cpu_do_core[6]}]

set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_a_core[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_a_core[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_a_core[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_a_core[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_a_core[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_a_core[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_a_core[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_a_core[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_a_core[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_a_core[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_a_core[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_a_core[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_a_core[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_a_core[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_a_core[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_a_core[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_do_core[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_do_core[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_do_core[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_do_core[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_do_core[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_do_core[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_do_core[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_cpu_do_core[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_cpu_di_core[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_cpu_di_core[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_cpu_di_core[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_cpu_di_core[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_cpu_di_core[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_cpu_di_core[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_cpu_di_core[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_cpu_di_core[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports i_clk_sys]
set_property IOSTANDARD LVCMOS33 [get_ports i_cpu_m1_l_core]
set_property IOSTANDARD LVCMOS33 [get_ports o_cpu_rst_core]
set_property IOSTANDARD LVCMOS33 [get_ports o_cpu_waitn]
set_property IOSTANDARD LVCMOS33 [get_ports o_do_core_enable_n]
set_property IOSTANDARD LVCMOS33 [get_ports o_flash_cs_l_core]
set_property IOSTANDARD LVCMOS33 [get_ports o_cpu_intn]
set_property IOSTANDARD LVCMOS33 [get_ports o_cpu_clk_core]
set_property IOSTANDARD LVCMOS33 [get_ports i_rst_sysn]
set_property IOSTANDARD LVCMOS33 [get_ports i_cpu_wr_l_core]
set_property IOSTANDARD LVCMOS33 [get_ports i_cpu_rfrsh_l_core]
set_property IOSTANDARD LVCMOS33 [get_ports i_cpu_rd_l_core]
set_property IOSTANDARD LVCMOS33 [get_ports i_cpu_mreq_l_core]
set_property PACKAGE_PIN C2 [get_ports o_cpu_intn]
set_property PACKAGE_PIN B3 [get_ports o_cpu_waitn]
set_property PACKAGE_PIN G1 [get_ports i_cpu_rfrsh_l_core]
set_property PACKAGE_PIN C6 [get_ports {i_cpu_a_core[8]}]
set_property PACKAGE_PIN P5 [get_ports i_rst_sysn]
set_property PACKAGE_PIN A3 [get_ports o_cpu_rst_core]





set_property PACKAGE_PIN E3 [get_ports {i_cpu_do_core[7]}]
set_property PACKAGE_PIN H2 [get_ports {i_cpu_do_core[5]}]
set_property PACKAGE_PIN K2 [get_ports {i_cpu_do_core[4]}]
set_property PACKAGE_PIN J2 [get_ports {i_cpu_do_core[3]}]
set_property PACKAGE_PIN E2 [get_ports {i_cpu_do_core[2]}]
set_property PACKAGE_PIN H1 [get_ports {i_cpu_do_core[0]}]
set_property PACKAGE_PIN G6 [get_ports {i_cpu_a_core[6]}]
set_property PACKAGE_PIN P3 [get_ports {o_cpu_di_core[1]}]
set_property PACKAGE_PIN F1 [get_ports {i_cpu_do_core[1]}]

set_property PULLDOWN true [get_ports {i_cpu_do_core[7]}]
set_property PULLDOWN true [get_ports {i_cpu_do_core[6]}]
set_property PULLDOWN true [get_ports {i_cpu_do_core[5]}]
set_property PULLDOWN true [get_ports {i_cpu_do_core[4]}]
set_property PULLDOWN true [get_ports {i_cpu_do_core[3]}]
set_property PULLDOWN true [get_ports {i_cpu_do_core[2]}]
set_property PULLDOWN true [get_ports {i_cpu_do_core[1]}]
set_property PULLDOWN true [get_ports {i_cpu_do_core[0]}]
set_property PULLDOWN true [get_ports {i_cpu_a_core[15]}]
set_property PULLDOWN true [get_ports {i_cpu_a_core[14]}]
set_property PULLDOWN true [get_ports {i_cpu_a_core[13]}]
set_property PULLDOWN true [get_ports {i_cpu_a_core[12]}]
set_property PULLDOWN true [get_ports {i_cpu_a_core[11]}]
set_property PULLDOWN true [get_ports {i_cpu_a_core[10]}]
set_property PULLDOWN true [get_ports {i_cpu_a_core[9]}]
set_property PULLDOWN true [get_ports {i_cpu_a_core[8]}]
set_property PULLDOWN true [get_ports {i_cpu_a_core[7]}]
set_property PULLDOWN true [get_ports {i_cpu_a_core[6]}]
set_property PULLDOWN true [get_ports {i_cpu_a_core[5]}]
set_property PULLDOWN true [get_ports {i_cpu_a_core[4]}]
set_property PULLDOWN true [get_ports {i_cpu_a_core[3]}]
set_property PULLDOWN true [get_ports {i_cpu_a_core[2]}]
set_property PULLDOWN true [get_ports {i_cpu_a_core[1]}]
set_property PULLDOWN true [get_ports {i_cpu_a_core[0]}]

set_property DRIVE 12 [get_ports {o_cpu_di_core[7]}]
set_property DRIVE 12 [get_ports {o_cpu_di_core[6]}]
set_property DRIVE 12 [get_ports {o_cpu_di_core[5]}]
set_property DRIVE 12 [get_ports {o_cpu_di_core[4]}]
set_property DRIVE 12 [get_ports {o_cpu_di_core[3]}]
set_property DRIVE 12 [get_ports {o_cpu_di_core[2]}]
set_property DRIVE 12 [get_ports {o_cpu_di_core[1]}]
set_property DRIVE 12 [get_ports {o_cpu_di_core[0]}]


set_property PACKAGE_PIN L18 [get_ports o_uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports o_uart_tx]

set_property PACKAGE_PIN M18 [get_ports i_uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports i_uart_rx]

set_property IOSTANDARD LVCMOS33 [get_ports {i_config_reg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_config_reg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_config_reg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_config_reg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_config_reg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_config_reg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_config_reg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_config_reg[0]}]
set_property PACKAGE_PIN R6 [get_ports {i_config_reg[0]}]
set_property PACKAGE_PIN V4 [get_ports {i_config_reg[1]}]
set_property PACKAGE_PIN T6 [get_ports {i_config_reg[2]}]
set_property PACKAGE_PIN V6 [get_ports {i_config_reg[3]}]
set_property PACKAGE_PIN T8 [get_ports {i_config_reg[4]}]
set_property PACKAGE_PIN V9 [get_ports {i_config_reg[5]}]
set_property PACKAGE_PIN N6 [get_ports {i_config_reg[6]}]
set_property PACKAGE_PIN U6 [get_ports {i_config_reg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vol[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vol[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vol[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vol[0]}]
set_property PACKAGE_PIN R5 [get_ports {o_vol[3]}]
set_property PACKAGE_PIN V5 [get_ports {o_vol[2]}]
set_property PACKAGE_PIN R7 [get_ports {o_vol[1]}]
set_property PACKAGE_PIN V7 [get_ports {o_vol[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_wav[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_wav[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_wav[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_wav[0]}]
set_property PACKAGE_PIN U7 [get_ports {o_wav[3]}]
set_property PACKAGE_PIN M6 [get_ports {o_wav[2]}]
set_property PACKAGE_PIN U9 [get_ports {o_wav[1]}]
set_property PACKAGE_PIN R8 [get_ports {o_wav[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports i_cpu_iorq_l]
set_property PACKAGE_PIN F3 [get_ports i_cpu_iorq_l]

set_property PACKAGE_PIN U2 [get_ports o_dip_l_cs]
set_property IOSTANDARD LVCMOS33 [get_ports o_dip_l_cs]
set_property IOSTANDARD LVCMOS33 [get_ports o_in0_l_cs]
set_property PACKAGE_PIN U1 [get_ports o_in0_l_cs]
set_property PACKAGE_PIN U3 [get_ports o_in1_l_cs]
set_property IOSTANDARD LVCMOS33 [get_ports o_in1_l_cs]

create_clock -period 19.231 -name clk_52M -waveform {0.000 9.616} [get_pins core_top_0/clk_gen_0/clk_52m]
set_clock_groups -name VGA -asynchronous -group [get_clocks -of_objects [get_pins core_top_0/clk_gen_0/clk_gen/inst/mmcm_adv_inst/CLKOUT1]]
set_clock_groups -name 52M -asynchronous -group [get_clocks clk_52M]
set_clock_groups -name SYSCLK -asynchronous -group [get_clocks -of_objects [get_pins core_top_0/clk_gen_0/clk_gen/inst/mmcm_adv_inst/CLKOUT2]]

create_clock -period 39.700 -name VGA_CLK -waveform {0.000 19.850} [get_nets core_top_0/clk_gen_0/clk_gen/clk_vga]
create_generated_clock -name CLK_6M -source [get_pins core_top_0/clk_gen_0/clk_gen/clk_sys] -edges {1 5 7} -edge_shift {0.000 0.000 0.000} [get_pins o_clk_6M_inferred_i_1/O]
create_generated_clock -name CLK_6M_STAR -source [get_pins core_top_0/clk_gen_0/clk_gen/clk_sys] -edges {3 5 9} -edge_shift {0.000 0.000 0.000} [get_pins o_clk_6M_star_n_inferred_i_1/O]
create_generated_clock -name CLK_Z80 -source [get_pins core_top_0/clk_gen_0/clk_gen/clk_sys] -edges {1 7 13} -edge_shift {0.000 0.000 0.000} [get_pins core_top_0/o_cpu_clk_core_OBUF]

set_property PACKAGE_PIN N1 [get_ports {o_vga[b_vga][2]}]
set_property PACKAGE_PIN R2 [get_ports {o_vga[b_vga][1]}]
set_property PACKAGE_PIN T1 [get_ports {o_vga[b_vga][0]}]
set_property PACKAGE_PIN N4 [get_ports {o_vga[g_vga][2]}]
set_property PACKAGE_PIN T3 [get_ports {o_vga[g_vga][0]}]
set_property PACKAGE_PIN T5 [get_ports {o_vga[r_vga][2]}]

set_property IOSTANDARD LVCMOS33 [get_ports {o_vga[b_vga][2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vga[b_vga][1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vga[b_vga][0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vga[g_vga][2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vga[g_vga][1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vga[g_vga][0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vga[r_vga][2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vga[r_vga][1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vga[r_vga][0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vga[hsync]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vga[vsync]}]



set_property IOSTANDARD LVCMOS33 [get_ports i_freeze]
set_property PACKAGE_PIN V2 [get_ports i_freeze]
set_property PULLUP true [get_ports i_freeze]


set_property OFFCHIP_TERM NONE [get_ports o_do_core_enable_n]
set_property OFFCHIP_TERM NONE [get_ports o_cpu_di_core[7]]
set_property OFFCHIP_TERM NONE [get_ports o_cpu_di_core[6]]
set_property OFFCHIP_TERM NONE [get_ports o_cpu_di_core[5]]
set_property OFFCHIP_TERM NONE [get_ports o_cpu_di_core[4]]
set_property OFFCHIP_TERM NONE [get_ports o_cpu_di_core[3]]
set_property OFFCHIP_TERM NONE [get_ports o_cpu_di_core[2]]
set_property OFFCHIP_TERM NONE [get_ports o_cpu_di_core[1]]
set_property OFFCHIP_TERM NONE [get_ports o_cpu_di_core[0]]
connect_debug_port u_ila_0/probe0 [get_nets [list {i_cpu_do_core_IBUF[0]} {i_cpu_do_core_IBUF[1]} {i_cpu_do_core_IBUF[2]} {i_cpu_do_core_IBUF[3]} {i_cpu_do_core_IBUF[4]} {i_cpu_do_core_IBUF[5]} {i_cpu_do_core_IBUF[6]} {i_cpu_do_core_IBUF[7]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {o_cpu_di_core_OBUF[0]} {o_cpu_di_core_OBUF[1]} {o_cpu_di_core_OBUF[2]} {o_cpu_di_core_OBUF[3]} {o_cpu_di_core_OBUF[4]} {o_cpu_di_core_OBUF[5]} {o_cpu_di_core_OBUF[6]} {o_cpu_di_core_OBUF[7]}]]

set_property PACKAGE_PIN C1 [get_ports {io_cpu_data_bidir[7]}]
set_property PACKAGE_PIN F4 [get_ports {io_cpu_data_bidir[6]}]
set_property PACKAGE_PIN H2 [get_ports {io_cpu_data_bidir[5]}]
set_property PACKAGE_PIN K2 [get_ports {io_cpu_data_bidir[4]}]
set_property PACKAGE_PIN J2 [get_ports {io_cpu_data_bidir[3]}]
set_property PACKAGE_PIN E2 [get_ports {io_cpu_data_bidir[2]}]
set_property PACKAGE_PIN F1 [get_ports {io_cpu_data_bidir[1]}]
set_property PACKAGE_PIN H1 [get_ports {io_cpu_data_bidir[0]}]
set_property PACKAGE_PIN P4 [get_ports {o_vga[g_vga][1]}]
set_property PACKAGE_PIN N5 [get_ports {o_vga[r_vga][1]}]
set_property PACKAGE_PIN V1 [get_ports {o_vga[r_vga][0]}]
set_property PACKAGE_PIN E1 [get_ports o_buffer_enable]
set_property PACKAGE_PIN D2 [get_ports o_buffer_dir]
set_property PACKAGE_PIN M3 [get_ports {o_vga[hsync]}]
set_property PACKAGE_PIN M1 [get_ports {o_vga[vsync]}]
set_property IOSTANDARD LVCMOS33 [get_ports o_buffer_dir]
set_property IOSTANDARD LVCMOS33 [get_ports o_buffer_enable]
set_property IOSTANDARD LVCMOS33 [get_ports {io_cpu_data_bidir[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_cpu_data_bidir[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_cpu_data_bidir[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_cpu_data_bidir[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_cpu_data_bidir[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_cpu_data_bidir[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_cpu_data_bidir[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_cpu_data_bidir[0]}]



connect_debug_port u_ila_0/clk [get_nets [list core_top_0/clk_gen_0/clk_gen/inst/clk_52m]]
connect_debug_port u_ila_0/probe3 [get_nets [list {core_top_0/u_Core/pacman_core_data[0]} {core_top_0/u_Core/pacman_core_data[1]} {core_top_0/u_Core/pacman_core_data[2]} {core_top_0/u_Core/pacman_core_data[3]} {core_top_0/u_Core/pacman_core_data[4]} {core_top_0/u_Core/pacman_core_data[5]} {core_top_0/u_Core/pacman_core_data[6]} {core_top_0/u_Core/pacman_core_data[7]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list o_buffer_enable_OBUF]]


set_property IOSTANDARD LVCMOS33 [get_ports o_buffer_enable_n]
set_property PACKAGE_PIN E1 [get_ports o_buffer_enable_n]

set_property OFFCHIP_TERM NONE [get_ports o_cpu_clk_core]
set_property OFFCHIP_TERM NONE [get_ports o_cpu_intn]
set_property OFFCHIP_TERM NONE [get_ports o_cpu_rst_core]
set_property OFFCHIP_TERM NONE [get_ports o_cpu_waitn]
set_property OFFCHIP_TERM NONE [get_ports o_flash_cs_l_core]
set_property SLEW SLOW [get_ports {io_cpu_data_bidir[7]}]
set_property SLEW SLOW [get_ports {io_cpu_data_bidir[6]}]
set_property SLEW SLOW [get_ports {io_cpu_data_bidir[5]}]
set_property SLEW SLOW [get_ports {io_cpu_data_bidir[4]}]
set_property SLEW SLOW [get_ports {io_cpu_data_bidir[3]}]
set_property SLEW SLOW [get_ports {io_cpu_data_bidir[2]}]
set_property SLEW SLOW [get_ports {io_cpu_data_bidir[1]}]
set_property SLEW SLOW [get_ports {io_cpu_data_bidir[0]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_gen_0/clk_gen/inst/clk_52m]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {io_cpu_data_bidir_IBUF[0]} {io_cpu_data_bidir_IBUF[1]} {io_cpu_data_bidir_IBUF[2]} {io_cpu_data_bidir_IBUF[3]} {io_cpu_data_bidir_IBUF[4]} {io_cpu_data_bidir_IBUF[5]} {io_cpu_data_bidir_IBUF[6]} {io_cpu_data_bidir_IBUF[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {i_cpu_a_core_IBUF[0]} {i_cpu_a_core_IBUF[1]} {i_cpu_a_core_IBUF[2]} {i_cpu_a_core_IBUF[3]} {i_cpu_a_core_IBUF[4]} {i_cpu_a_core_IBUF[5]} {i_cpu_a_core_IBUF[6]} {i_cpu_a_core_IBUF[7]} {i_cpu_a_core_IBUF[8]} {i_cpu_a_core_IBUF[9]} {i_cpu_a_core_IBUF[10]} {i_cpu_a_core_IBUF[11]} {i_cpu_a_core_IBUF[12]} {i_cpu_a_core_IBUF[13]} {i_cpu_a_core_IBUF[14]} {i_cpu_a_core_IBUF[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {io_cpu_data_bidir_OBUF[0]} {io_cpu_data_bidir_OBUF[1]} {io_cpu_data_bidir_OBUF[2]} {io_cpu_data_bidir_OBUF[3]} {io_cpu_data_bidir_OBUF[4]} {io_cpu_data_bidir_OBUF[5]} {io_cpu_data_bidir_OBUF[6]} {io_cpu_data_bidir_OBUF[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list i_cpu_m1_l_core_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list i_cpu_mreq_l_core_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list i_cpu_rd_l_core_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list i_cpu_rfrsh_l_core_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list i_cpu_wr_l_core_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list o_buffer_dir_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list o_buffer_enable_n_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list o_cpu_clk_core_OBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list o_cpu_waitn_OBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets i_clk_52m]
