
set_property PACKAGE_PIN V6 [get_ports o_dip_l_cs]
set_property PACKAGE_PIN T6 [get_ports o_in0_l_cs]
set_property PACKAGE_PIN V7 [get_ports o_in1_l_cs]
set_property PACKAGE_PIN M2 [get_ports {o_vga[r_vga][0]}]
set_property PACKAGE_PIN N6 [get_ports {i_config_reg[4]}]
set_property PACKAGE_PIN U7 [get_ports {i_config_reg[7]}]
set_property PACKAGE_PIN U6 [get_ports {i_config_reg[6]}]
set_property PACKAGE_PIN T8 [get_ports {i_config_reg[0]}]
set_property PACKAGE_PIN R8 [get_ports {i_config_reg[1]}]

set_property DRIVE 12 [get_ports {o_audio_vol_out[3]}]
set_property DRIVE 12 [get_ports {o_audio_vol_out[2]}]
set_property DRIVE 12 [get_ports {o_audio_vol_out[1]}]
set_property DRIVE 12 [get_ports {o_audio_vol_out[0]}]
set_property SLEW SLOW [get_ports {o_audio_vol_out[3]}]
set_property SLEW SLOW [get_ports {o_audio_vol_out[2]}]
set_property SLEW SLOW [get_ports {o_audio_vol_out[1]}]
set_property SLEW SLOW [get_ports {o_audio_vol_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_config_reg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_config_reg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_config_reg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_config_reg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_config_reg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_config_reg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_config_reg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_config_reg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_audio_vol_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_audio_vol_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_audio_vol_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_audio_vol_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_audio_wav_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_audio_wav_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_audio_wav_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_audio_wav_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vga[b_vga][2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vga[b_vga][1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vga[b_vga][0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vga[g_vga][2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vga[g_vga][1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vga[g_vga][0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vga[r_vga][2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vga[r_vga][1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vga[r_vga][0]}]
set_property IOSTANDARD LVCMOS33 [get_ports o_dip_l_cs]
set_property IOSTANDARD LVCMOS33 [get_ports o_in0_l_cs]
set_property IOSTANDARD LVCMOS33 [get_ports o_in1_l_cs]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vga[hsync]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_vga[vsync]}]


set_property IOSTANDARD LVCMOS33 [get_ports i_rst_sys_n]
set_property PACKAGE_PIN C6 [get_ports i_rst_sys_n]
set_property PACKAGE_PIN U9 [get_ports {i_config_reg[3]}]
set_property PACKAGE_PIN M6 [get_ports {i_config_reg[5]}]
set_property PACKAGE_PIN P5 [get_ports {o_audio_vol_out[3]}]
set_property PACKAGE_PIN R3 [get_ports {o_audio_wav_out[3]}]
set_property PACKAGE_PIN P4 [get_ports {o_audio_wav_out[2]}]
set_property PACKAGE_PIN P3 [get_ports {o_audio_wav_out[1]}]
set_property PACKAGE_PIN N4 [get_ports {o_audio_wav_out[0]}]
set_property PACKAGE_PIN R1 [get_ports {o_vga[b_vga][2]}]
set_property PACKAGE_PIN T5 [get_ports {o_audio_vol_out[2]}]
set_property PACKAGE_PIN T4 [get_ports {o_audio_vol_out[1]}]
set_property PACKAGE_PIN T3 [get_ports {o_audio_vol_out[0]}]
set_property PACKAGE_PIN R2 [get_ports {o_vga[b_vga][1]}]
set_property PACKAGE_PIN P2 [get_ports {o_vga[b_vga][0]}]
set_property PACKAGE_PIN N1 [get_ports {o_vga[g_vga][2]}]
set_property PACKAGE_PIN N2 [get_ports {o_vga[g_vga][1]}]
set_property PACKAGE_PIN M1 [get_ports {o_vga[g_vga][0]}]
set_property PACKAGE_PIN L1 [get_ports {o_vga[r_vga][2]}]
set_property PACKAGE_PIN M3 [get_ports {o_vga[r_vga][1]}]
set_property PACKAGE_PIN T1 [get_ports {o_vga[hsync]}]
set_property PACKAGE_PIN M4 [get_ports {o_vga[vsync]}]





