# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/yannv/Documents/Projets_HW/PacMan/PacMan_v2_AIO/Pacman_Artyx7/Pacman_Artyx7.srcs/sources_1/ip/pacman_ram_v2/pacman_ram_v2.xci
# IP: The module: 'pacman_ram_v2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yannv/Documents/Projets_HW/PacMan/PacMan_v2_AIO/Pacman_Artyx7/Pacman_Artyx7.gen/sources_1/ip/pacman_ram_v2/pacman_ram_v2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pacman_ram_v2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/yannv/Documents/Projets_HW/PacMan/PacMan_v2_AIO/Pacman_Artyx7/Pacman_Artyx7.srcs/sources_1/ip/pacman_ram_v2/pacman_ram_v2.xci
# IP: The module: 'pacman_ram_v2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yannv/Documents/Projets_HW/PacMan/PacMan_v2_AIO/Pacman_Artyx7/Pacman_Artyx7.gen/sources_1/ip/pacman_ram_v2/pacman_ram_v2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pacman_ram_v2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
