# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

<<<<<<< HEAD
# IP: C:/Users/yannv/Documents/Projets_HW/PacMan_v2_AIO/Pacman_Artyx7/Pacman_Artyx7.srcs/sources_1/ip/blk_mem_gen_video_ram/blk_mem_gen_video_ram.xci
# IP: The module: 'blk_mem_gen_video_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yannv/Documents/Projets_HW/PacMan_v2_AIO/Pacman_Artyx7/Pacman_Artyx7.gen/sources_1/ip/blk_mem_gen_video_ram/blk_mem_gen_video_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_video_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/yannv/Documents/Projets_HW/PacMan_v2_AIO/Pacman_Artyx7/Pacman_Artyx7.srcs/sources_1/ip/blk_mem_gen_video_ram/blk_mem_gen_video_ram.xci
# IP: The module: 'blk_mem_gen_video_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yannv/Documents/Projets_HW/PacMan_v2_AIO/Pacman_Artyx7/Pacman_Artyx7.gen/sources_1/ip/blk_mem_gen_video_ram/blk_mem_gen_video_ram_ooc.xdc
=======
# IP: C:/Users/yannv/Documents/Projets_HW/PacMan_v2/Pacman_Artyx7/Pacman_Artyx7.srcs/sources_1/ip/blk_mem_gen_video_ram/blk_mem_gen_video_ram.xci
# IP: The module: 'blk_mem_gen_video_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yannv/Documents/Projets_HW/PacMan_v2/Pacman_Artyx7/Pacman_Artyx7.gen/sources_1/ip/blk_mem_gen_video_ram/blk_mem_gen_video_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_video_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/yannv/Documents/Projets_HW/PacMan_v2/Pacman_Artyx7/Pacman_Artyx7.srcs/sources_1/ip/blk_mem_gen_video_ram/blk_mem_gen_video_ram.xci
# IP: The module: 'blk_mem_gen_video_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/yannv/Documents/Projets_HW/PacMan_v2/Pacman_Artyx7/Pacman_Artyx7.gen/sources_1/ip/blk_mem_gen_video_ram/blk_mem_gen_video_ram_ooc.xdc
>>>>>>> 8d8951fe53392006346f0a5ba26bbcbabd6294a8
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_video_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
